name: html_tagged_text
description: A widget to style text using custom HTML tags.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
